// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANj53IX7K9Qnp4kZTVGqvMiGJsWT0WSsc',
    appId: '1:805547555691:web:86c94b08c6172846006a2e',
    messagingSenderId: '805547555691',
    projectId: 'tubes-64e0d',
    authDomain: 'tubes-64e0d.firebaseapp.com',
    databaseURL: 'https://tubes-64e0d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tubes-64e0d.appspot.com',
    measurementId: 'G-0PVGRFW7FC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-P6YQLSoKn4OUn6VBkDpuI0yDNvFMaLE',
    appId: '1:805547555691:android:22c96d2bcf507a4f006a2e',
    messagingSenderId: '805547555691',
    projectId: 'tubes-64e0d',
    databaseURL: 'https://tubes-64e0d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tubes-64e0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5L0JRtR0us6uX9avz-FG3n6qLX-szRBo',
    appId: '1:805547555691:ios:5acf77a300a91824006a2e',
    messagingSenderId: '805547555691',
    projectId: 'tubes-64e0d',
    databaseURL: 'https://tubes-64e0d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tubes-64e0d.appspot.com',
    iosClientId: '805547555691-1nl9ceceu561se0a8jv1q1sj9i2tthi7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTravelUiStarter',
  );
}
